---
- name: Install Nginx
  apt:  name=nginx state=present
  tags:
    - web
    - infra
  sudo: yes

- name: Install python-passlib (required by htpasswd module)
  apt: name=python-passlib state=present
  sudo: yes
  tags:
    - web
    - infra

- name: Create password file
  htpasswd: name={{ webserver_user }} password={{ webserver_password }} path=/etc/nginx/auth-passwd state=present
  sudo: yes
  tags:
    - web
    - infra

- name: Validate that nginx is installed
  uri:  url=http://127.0.0.1
  tags: web

- name: Create static root dir
  file: path=/var/www/workshop state=directory owner=www-data group=www-data
  sudo: yes
  tags: web

- name: Copy static HTML files to root dir
  template: src=index.html.template dest=/var/www/workshop/index.html owner=www-data group=www-data
  sudo: yes
  tags: web
  notify:
    - Reload nginx

- name: Disable default site in Nginx
  file: path=/etc/nginx/sites-enabled/default state=absent
  tags: web
  sudo: yes

- name: Generate our own nginx site
  template: src=site.conf.template dest=/etc/nginx/sites-available/site.conf owner=www-data group=www-data
  sudo: yes
  tags: web
  notify:
    - Reload nginx

- name: Symlink our nginx site
  file: state=link src=/etc/nginx/sites-available/site.conf path=/etc/nginx/sites-enabled/site.conf owner=www-data group=www-data
  sudo: yes
  tags: web
  notify:
    - Reload nginx
